# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNegativeTestHandphonenotvalid():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_negativeTestHandphonenotvalid(self):
    # Test name: Negative Test - Handphone not valid
    # Step # | name | target | value
    # 1 | open | /app/gabung | 
    self.driver.get("https://www.cermati.com/app/gabung")
    # 2 | setWindowSize | 1296x696 | 
    self.driver.set_window_size(1296, 696)
    # 3 | click | id=mobilePhone | 
    self.driver.find_element(By.ID, "mobilePhone").click()
    # 4 | type | id=mobilePhone | 111896829966981111
    self.driver.find_element(By.ID, "mobilePhone").send_keys("111896829966981111")
    # 5 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 6 | type | id=email | nino.stenfidz87@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("nino.stenfidz87@gmail.com")
    # 7 | click | id=firstName | 
    self.driver.find_element(By.ID, "firstName").click()
    # 8 | type | id=firstName | Rendra
    self.driver.find_element(By.ID, "firstName").send_keys("Rendra")
    # 9 | click | id=lastName | 
    self.driver.find_element(By.ID, "lastName").click()
    # 10 | type | id=lastName | Dwi Pranoto
    self.driver.find_element(By.ID, "lastName").send_keys("Dwi Pranoto")
    # 11 | click | css=.RegistrationForm_form-container__button-text__G_fL8 | 
    self.driver.find_element(By.CSS_SELECTOR, ".RegistrationForm_form-container__button-text__G_fL8").click()
    # 12 | pause | 3000 | 
    time.sleep(3000)
  
